<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            [
                'name'            => 'Dubrovnik',
                'slug'            => 'dubrovnik',
                'region'          => 'Dalmatia South',
                'latitude'        => 42.650661,
                'longitude'       => 18.094424,
                'beach_score'     => 8,
                'culture_score'   => 10,
                'active_score'    => 6,
                'gastronomy_score'=> 9,
                'family_score'    => 6,
                'budget_tier'     => 4,
                'min_stay_days'   => 2,
                'max_stay_days'   => 4,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'UNESCO-listed walled city with stunning Adriatic views.',
            ],
            [
                'name'            => 'Split',
                'slug'            => 'split',
                'region'          => 'Dalmatia Central',
                'latitude'        => 43.508133,
                'longitude'       => 16.440193,
                'beach_score'     => 7,
                'culture_score'   => 10,
                'active_score'    => 7,
                'gastronomy_score'=> 8,
                'family_score'    => 7,
                'budget_tier'     => 3,
                'min_stay_days'   => 2,
                'max_stay_days'   => 4,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'Vibrant city built around Diocletian\'s Palace, gateway to Dalmatian islands.',
            ],
            [
                'name'            => 'Hvar',
                'slug'            => 'hvar',
                'region'          => 'Dalmatia Central',
                'latitude'        => 43.172992,
                'longitude'       => 16.441344,
                'beach_score'     => 9,
                'culture_score'   => 7,
                'active_score'    => 7,
                'gastronomy_score'=> 8,
                'family_score'    => 5,
                'budget_tier'     => 4,
                'min_stay_days'   => 2,
                'max_stay_days'   => 4,
                'car_accessible'  => false,
                'plane_accessible'=> false,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September'],
                'description'     => 'Lavender-scented island known for nightlife, beaches, and historic towns.',
            ],
            [
                'name'            => 'Korčula',
                'slug'            => 'korcula',
                'region'          => 'Dalmatia South',
                'latitude'        => 42.960266,
                'longitude'       => 17.135548,
                'beach_score'     => 8,
                'culture_score'   => 9,
                'active_score'    => 6,
                'gastronomy_score'=> 8,
                'family_score'    => 7,
                'budget_tier'     => 3,
                'min_stay_days'   => 2,
                'max_stay_days'   => 3,
                'car_accessible'  => false,
                'plane_accessible'=> false,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'Medieval island town, birthplace of Marco Polo, surrounded by vineyards.',
            ],
            [
                'name'            => 'Zadar',
                'slug'            => 'zadar',
                'region'          => 'Dalmatia North',
                'latitude'        => 44.119371,
                'longitude'       => 15.231365,
                'beach_score'     => 7,
                'culture_score'   => 8,
                'active_score'    => 5,
                'gastronomy_score'=> 7,
                'family_score'    => 8,
                'budget_tier'     => 2,
                'min_stay_days'   => 1,
                'max_stay_days'   => 3,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'Ancient Roman city with the famous Sea Organ and Greeting to the Sun.',
            ],
            [
                'name'            => 'Šibenik',
                'slug'            => 'sibenik',
                'region'          => 'Dalmatia North',
                'latitude'        => 43.735949,
                'longitude'       => 15.895116,
                'beach_score'     => 6,
                'culture_score'   => 8,
                'active_score'    => 5,
                'gastronomy_score'=> 7,
                'family_score'    => 8,
                'budget_tier'     => 2,
                'min_stay_days'   => 1,
                'max_stay_days'   => 2,
                'car_accessible'  => true,
                'plane_accessible'=> false,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'UNESCO cathedral city, perfect base for Krka National Park.',
            ],
            [
                'name'            => 'Trogir',
                'slug'            => 'trogir',
                'region'          => 'Dalmatia Central',
                'latitude'        => 43.516388,
                'longitude'       => 16.251389,
                'beach_score'     => 6,
                'culture_score'   => 9,
                'active_score'    => 4,
                'gastronomy_score'=> 7,
                'family_score'    => 7,
                'budget_tier'     => 2,
                'min_stay_days'   => 1,
                'max_stay_days'   => 2,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'Tiny UNESCO island city, well-preserved medieval architecture.',
            ],
            [
                'name'            => 'Makarska',
                'slug'            => 'makarska',
                'region'          => 'Dalmatia Central',
                'latitude'        => 43.296547,
                'longitude'       => 17.018339,
                'beach_score'     => 9,
                'culture_score'   => 5,
                'active_score'    => 8,
                'gastronomy_score'=> 6,
                'family_score'    => 8,
                'budget_tier'     => 2,
                'min_stay_days'   => 2,
                'max_stay_days'   => 5,
                'car_accessible'  => true,
                'plane_accessible'=> false,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September'],
                'description'     => 'Riviera resort beneath Biokovo mountain, great beaches and hiking.',
            ],
            [
                'name'            => 'Brela',
                'slug'            => 'brela',
                'region'          => 'Dalmatia Central',
                'latitude'        => 43.370000,
                'longitude'       => 16.930000,
                'beach_score'     => 10,
                'culture_score'   => 3,
                'active_score'    => 6,
                'gastronomy_score'=> 5,
                'family_score'    => 9,
                'budget_tier'     => 2,
                'min_stay_days'   => 2,
                'max_stay_days'   => 5,
                'car_accessible'  => true,
                'plane_accessible'=> false,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September'],
                'description'     => 'One of Croatia\'s most beautiful pebble beaches backed by pine forests.',
            ],
            [
                'name'            => 'Vis',
                'slug'            => 'vis',
                'region'          => 'Dalmatia Central',
                'latitude'        => 43.058333,
                'longitude'       => 16.180556,
                'beach_score'     => 9,
                'culture_score'   => 6,
                'active_score'    => 7,
                'gastronomy_score'=> 9,
                'family_score'    => 5,
                'budget_tier'     => 3,
                'min_stay_days'   => 2,
                'max_stay_days'   => 4,
                'car_accessible'  => false,
                'plane_accessible'=> false,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September'],
                'description'     => 'Remote, unspoiled island with crystal waters and top Dalmatian cuisine.',
            ],
            [
                'name'            => 'Mljet',
                'slug'            => 'mljet',
                'region'          => 'Dalmatia South',
                'latitude'        => 42.743611,
                'longitude'       => 17.535556,
                'beach_score'     => 8,
                'culture_score'   => 5,
                'active_score'    => 9,
                'gastronomy_score'=> 5,
                'family_score'    => 7,
                'budget_tier'     => 2,
                'min_stay_days'   => 2,
                'max_stay_days'   => 3,
                'car_accessible'  => false,
                'plane_accessible'=> false,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'National park island with saltwater lakes and cycling trails.',
            ],
            [
                'name'            => 'Opatija',
                'slug'            => 'opatija',
                'region'          => 'Kvarner',
                'latitude'        => 45.337222,
                'longitude'       => 14.308056,
                'beach_score'     => 6,
                'culture_score'   => 8,
                'active_score'    => 7,
                'gastronomy_score'=> 9,
                'family_score'    => 7,
                'budget_tier'     => 3,
                'min_stay_days'   => 2,
                'max_stay_days'   => 4,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August', 'September'],
                'shoulder_months' => ['April', 'May', 'October'],
                'description'     => 'Elegant Austro-Hungarian riviera town with a scenic coastal promenade.',
            ],
            [
                'name'            => 'Rijeka',
                'slug'            => 'rijeka',
                'region'          => 'Kvarner',
                'latitude'        => 45.327063,
                'longitude'       => 14.442176,
                'beach_score'     => 3,
                'culture_score'   => 8,
                'active_score'    => 5,
                'gastronomy_score'=> 8,
                'family_score'    => 6,
                'budget_tier'     => 1,
                'min_stay_days'   => 1,
                'max_stay_days'   => 2,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['April', 'May', 'September', 'October'],
                'description'     => 'Croatia\'s main port city with vibrant street art and café culture.',
            ],
            [
                'name'            => 'Cres',
                'slug'            => 'cres',
                'region'          => 'Kvarner',
                'latitude'        => 44.959722,
                'longitude'       => 14.410556,
                'beach_score'     => 7,
                'culture_score'   => 5,
                'active_score'    => 9,
                'gastronomy_score'=> 6,
                'family_score'    => 6,
                'budget_tier'     => 1,
                'min_stay_days'   => 2,
                'max_stay_days'   => 4,
                'car_accessible'  => true,
                'plane_accessible'=> false,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'Rugged, undiscovered island with griffon vultures and secluded coves.',
            ],
            [
                'name'            => 'Lošinj',
                'slug'            => 'losinj',
                'region'          => 'Kvarner',
                'latitude'        => 44.531944,
                'longitude'       => 14.468056,
                'beach_score'     => 8,
                'culture_score'   => 6,
                'active_score'    => 8,
                'gastronomy_score'=> 7,
                'family_score'    => 8,
                'budget_tier'     => 3,
                'min_stay_days'   => 2,
                'max_stay_days'   => 5,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'Aromatic island known as a health resort, dolphins, and wellness.',
            ],
            [
                'name'            => 'Rovinj',
                'slug'            => 'rovinj',
                'region'          => 'Istria',
                'latitude'        => 45.080556,
                'longitude'       => 13.638889,
                'beach_score'     => 7,
                'culture_score'   => 9,
                'active_score'    => 5,
                'gastronomy_score'=> 9,
                'family_score'    => 7,
                'budget_tier'     => 3,
                'min_stay_days'   => 2,
                'max_stay_days'   => 4,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['April', 'May', 'September', 'October'],
                'description'     => 'Picturesque hilltop old town on a peninsula, Istria\'s romantic gem.',
            ],
            [
                'name'            => 'Poreč',
                'slug'            => 'porec',
                'region'          => 'Istria',
                'latitude'        => 45.226944,
                'longitude'       => 13.596389,
                'beach_score'     => 8,
                'culture_score'   => 8,
                'active_score'    => 6,
                'gastronomy_score'=> 8,
                'family_score'    => 9,
                'budget_tier'     => 2,
                'min_stay_days'   => 2,
                'max_stay_days'   => 5,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['May', 'September', 'October'],
                'description'     => 'Family resort town with UNESCO Euphrasian Basilica and water parks.',
            ],
            [
                'name'            => 'Pula',
                'slug'            => 'pula',
                'region'          => 'Istria',
                'latitude'        => 44.866667,
                'longitude'       => 13.850000,
                'beach_score'     => 7,
                'culture_score'   => 10,
                'active_score'    => 5,
                'gastronomy_score'=> 8,
                'family_score'    => 8,
                'budget_tier'     => 2,
                'min_stay_days'   => 2,
                'max_stay_days'   => 4,
                'car_accessible'  => true,
                'plane_accessible'=> true,
                'peak_months'     => ['June', 'July', 'August'],
                'shoulder_months' => ['April', 'May', 'September', 'October'],
                'description'     => 'Roman amphitheatre city at Istria\'s tip, superb seafood and history.',
            ],
            [
                'name'            => 'Plitvice Lakes',
                'slug'            => 'plitvice-lakes',
                'region'          => 'Central Croatia',
                'latitude'        => 44.880278,
                'longitude'       => 15.616944,
                'beach_score'     => 2,
                'culture_score'   => 6,
                'active_score'    => 10,
                'gastronomy_score'=> 5,
                'family_score'    => 8,
                'budget_tier'     => 2,
                'min_stay_days'   => 1,
                'max_stay_days'   => 2,
                'car_accessible'  => true,
                'plane_accessible'=> false,
                'peak_months'     => ['May', 'June', 'July', 'August', 'September'],
                'shoulder_months' => ['April', 'October'],
                'description'     => 'UNESCO world wonder — 16 terraced lakes with cascading turquoise waterfalls.',
            ],
            [
                'name'            => 'Krka National Park',
                'slug'            => 'krka',
                'region'          => 'Dalmatia North',
                'latitude'        => 43.808611,
                'longitude'       => 15.970556,
                'beach_score'     => 7,
                'culture_score'   => 5,
                'active_score'    => 10,
                'gastronomy_score'=> 5,
                'family_score'    => 9,
                'budget_tier'     => 2,
                'min_stay_days'   => 1,
                'max_stay_days'   => 2,
                'car_accessible'  => true,
                'plane_accessible'=> false,
                'peak_months'     => ['May', 'June', 'July', 'August', 'September'],
                'shoulder_months' => ['April', 'October'],
                'description'     => 'Stunning river canyon with swimmable waterfalls and medieval monasteries.',
            ],
        ];

        foreach ($locations as $location) {
            Location::create($location);
        }
    }
}
